# Generated by Django 4.2.1 on 2024-05-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='articulos',
            name='marca',
            field=models.CharField(default='Sin Marca', max_length=30),
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio_oferta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
