# Generated by Django 5.0.4 on 2024-05-31 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_carrito_carritoarticulo_carrito_articulos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoarticulo',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoarticulo',
            name='articulo',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='menu.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoArticulo',
        ),
    ]
