# Generated by Django 5.0.4 on 2024-07-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_recepcionproducto_carrito_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcionproducto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='recepcionproducto',
            name='en_resumen',
        ),
        migrations.RemoveField(
            model_name='recepcionproducto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='recepcionproducto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='recepcionproducto',
            name='precio_venta',
        ),
    ]
