# Generated by Django 5.0.4 on 2024-07-01 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_recepcionproducto_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecepcionProducto',
        ),
    ]
