# Generated by Django 5.0.4 on 2024-05-31 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='articulo',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
