# Generated by Django 5.0.4 on 2024-05-31 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_cartitem_cart_remove_cartitem_articulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.ImageField(upload_to='static/img/')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='menu.articulos')),
            ],
        ),
    ]
