# Generated by Django 5.0.4 on 2024-07-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_delete_proveedorcarritoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProveedorCarrito',
        ),
    ]
