# Generated by Django 5.0.4 on 2024-07-01 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_delete_proveedorcarrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductosProveedor',
        ),
    ]
