# Generated by Django 5.0.4 on 2024-06-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_carrito_carritoitem_delete_fotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
