# Generated by Django 4.2.1 on 2024-06-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_usuario_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='precio_envio',
            field=models.IntegerField(default=1),
        ),
    ]
