# Generated by Django 5.0.4 on 2024-06-11 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_usuario_direccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
