# Generated by Django 5.0.4 on 2024-06-11 03:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_orden_compra', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.proveedor')),
            ],
        ),
    ]
