# Generated by Django 5.0.4 on 2024-06-11 03:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlativo', models.IntegerField(editable=False)),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Costo')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub Total')),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.articulos', verbose_name='Articulos')),
                ('id_orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='menu.compra')),
            ],
            options={
                'unique_together': {('id_orden_compra', 'correlativo')},
            },
        ),
    ]
