# Generated by Django 5.0.4 on 2024-06-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_populate_comunas'),
        ('menu', '0018_detallecompra'),
    ]

    operations = [
    ]
