# Generated by Django 5.0.4 on 2024-06-13 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_merge_0016_populate_comunas_0018_detallecompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='precio_costo',
        ),
        migrations.CreateModel(
            name='ProductosProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('foto_producto', models.ImageField(upload_to='productos_proveedor/', verbose_name='Foto del Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='menu.proveedor')),
            ],
        ),
    ]
