# Generated by Django 5.0.4 on 2024-06-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_remove_detallecompra_precio_costo_productosproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosproveedor',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Precio de Costo'),
            preserve_default=False,
        ),
    ]
