# Generated by Django 5.0.4 on 2024-06-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_proveedorcarritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorcarritoitem',
            name='cantidad_llegada',
            field=models.IntegerField(default=0),
        ),
    ]
