# Generated by Django 5.0.4 on 2024-06-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_proveedorcarritoitem_cantidad_llegada'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorcarritoitem',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
    ]
