# Generated by Django 5.0.4 on 2024-06-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_usuario_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='articulo',
        ),
    ]
