# Generated by Django 5.0.4 on 2024-06-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_remove_imagen_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedorcarritoitem',
            name='aceptado',
        ),
        migrations.RemoveField(
            model_name='proveedorcarritoitem',
            name='agregado_en',
        ),
        migrations.RemoveField(
            model_name='proveedorcarritoitem',
            name='cantidad_llegada',
        ),
        migrations.RemoveField(
            model_name='proveedorcarritoitem',
            name='en_resumen',
        ),
    ]
