# Generated by Django 5.0.4 on 2024-06-28 02:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_remove_proveedorcarritoitem_aceptado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_llegada', models.IntegerField(default=0)),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmado', models.BooleanField(default=False)),
                ('en_resumen', models.BooleanField(default=True)),
                ('carrito_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='menu.proveedorcarritoitem')),
            ],
        ),
    ]
