# Generated by Django 5.0.4 on 2024-06-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_recepcionproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcionproducto',
            name='carrito_item',
        ),
    ]
