# Generated by Django 5.0.4 on 2024-06-28 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0031_remove_recepcionproducto_carrito_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionproducto',
            name='carrito_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='menu.proveedorcarritoitem'),
            preserve_default=False,
        ),
    ]
