# Generated by Django 5.0.4 on 2024-06-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0032_recepcionproducto_carrito_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorcarritoitem',
            name='en_resumen',
            field=models.BooleanField(default=True),
        ),
    ]
