# Generated by Django 5.0.4 on 2024-06-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_proveedorcarritoitem_en_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionproducto',
            name='descripcion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcionproducto',
            name='marca',
            field=models.CharField(default='Sin Marca', max_length=30),
        ),
        migrations.AddField(
            model_name='recepcionproducto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Precio de venta'),
            preserve_default=False,
        ),
    ]
