# Generated by Django 5.0.6 on 2024-06-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_proveedorcarritoitem_en_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('BODEGA', 'Bodeguero'), ('CLIENT', 'Cliente')], default='CLIENT', max_length=6),
        ),
    ]
