# Generated by Django 5.0.4 on 2024-06-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0034_recepcionproducto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionproducto',
            name='estado',
            field=models.CharField(default='en_resumen', max_length=20),
        ),
    ]
