# Generated by Django 5.0.6 on 2024-06-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0034_remove_usuario_groups_usuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('BODEGA', 'Bodeguero'), ('CLIENT', 'Cliente')], max_length=6),
        ),
    ]
